REMOTE_MEDIA_PLAYER_INTERFACE = "com.kentkart.RemoteMediaPlayer"
MEDIA_INTERFACE = "com.kentkart.RemoteMediaPlayer.Media"
AUDIO_INTERFACE = "com.kentkart.RemoteMediaPlayer.Media.Audio"
VIDEO_INTERFACE = "com.kentkart.RemoteMediaPlayer.Media.Video"
PROPERTIES_INTERFACE = "org.freedesktop.DBus.Properties"